file:
  path: C:/mp3_test

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://192.168.219.10:3306/mp3?serverTimezone=UTC&characterEncoding=UTF-8
    url: jdbc:mariadb://localhost:3306/mp3?serverTimezone=UTC&characterEncoding=UTF-8
    username: peter
    password: saint215

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: none

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE